### ISSUE TITLE
Schedule to ICS

### ISSUE THREAD

**Issue by tachalainen** [Balazs-topg/nar-slutar-lektionen#1]
Hey,

A suggestion that we're a lot of people looking for.

Choose the school and class.
Export the schedule to an ICS file in which you can import to your calendar.

Is this doable?

Thanks!

**Comment by balazshevesi** [comment]
Hello!

I haven't worked with ICS-files before, as i understand it's a plain text file format made for storing calendar events, to me it looks kinda similar to JSON.

It's 100% doable, but I'm not gonna add it since i don't think it suits the project.

---

If you look at the README-file under "Skola24as API" I've documented how the API works and all of the API calls you need to make inorder to get the schedule. I've even linked the steps to the typescript-files.

I'd recommend using Postman to experiment with the API, and a scripting language like Python, Javascript/Typescript, Lua, or C# to do the API calls in sequence, then just convert the API's JSON response to a string that resembles the ICS-format, then just write that string to an ICS file. It should be fairly simple.

On step 5, if i recall correctly, "scheduleDay" 1 to 5 represents Monday to Friday, 6 gives an error, and 0 returns the schedule for the whole week.

The API can be a bitch sometimes, feel free to email me if you've got any questions.
